### ISSUE TITLE
fix truffle test failure

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/plasma-contracts#652]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
CI is failing on truffle testing

**Comment by boolafish** [comment]
might be related: https://github.com/ethereum/web3.js/issues/3425

**Comment by boolafish** [comment]
current investigation:

It was originally failing with `Cannot find module 'eth-json-rpc-filters'`. So I tried to do some update on npm package via `npm audit fix` and seems to fix that error.

However, we now face different error:

```
/home/circleci/repo/plasma_framework/node_modules/web3-core-helpers/src/errors.js:42
 
        return new Error(message);
 
               ^
 
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
 
Error: Invalid JSON RPC response: ""
 
    at Object.InvalidResponse (/home/circleci/repo/plasma_framework/node_modules/web3-core-helpers/src/errors.js:42:16)
 
    at XMLHttpRequest.request.onreadystatechange (/home/circleci/repo/plasma_framework/node_modules/web3-providers-http/src/index.js:92:32)
 
    at XMLHttpRequestEventTarget.dispatchEvent (/home/circleci/repo/plasma_framework/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
 
    at XMLHttpRequest._setReadyState (/home/circleci/repo/plasma_framework/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
 
    at XMLHttpRequest._onHttpRequestError (/home/circleci/repo/plasma_framework/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
 
    at ClientRequest.<anonymous> (/home/circleci/repo/plasma_framework/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
 
    at ClientRequest.emit (events.js:198:13)
 
    at Socket.socketErrorListener (_http_client.js:401:9)
 
    at Socket.emit (events.js:198:13)
 
    at emitErrorNT (internal/streams/destroy.js:91:8)
 
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
 
    at process._tickCallback (internal/process/next_tick.js:63:19)
 
    at PollingBlockTracker._performSync (/home/circleci/repo/plasma_framework/node_modules/web3-provider-engine/node_modules/eth-block-tracker/src/polling.js:51:24)
 
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ```

**Comment by boolafish** [comment]
seems like some issue on the hd-wallet

after this commit: https://github.com/omgnetwork/plasma-contracts/pull/651/commits/51203f278587a2fdd2754715210f3fea1e98c830 it start to run the test......

**Comment by boolafish** [comment]
Some guy had send a PR to truffle to fix this issue:
- https://github.com/trufflesuite/truffle/issues/3130
- https://github.com/trufflesuite/provider-engine/pull/6

Potentially it is caused by truffle has its own fork of some dependency so did not get the fix....
